spring:
  mvc: 
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp
# 数据库驱动配置   
  datasource:
    url: jdbc:mysql://47.100.215.44:3306/shoesMall
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver
# 添加  默认使用jackson解析 设置日期格式  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
      
# 邮件服务配置
  mail:
    # 邮箱服务器地址
    host: smtp.qq.com
    # 用户名
    username: 1761428840@qq.com
    # 发送密码
    password: 
    # 默认字符集编码
    default-encoding: UTF-8
# 发送地址   
mail:
  fromMail:
    addr: 1761428840@qq.com
    
# 日志输出
logging:
  level:
    com:
      yc: debug

 